### ISSUE TITLE
MILRET muscle version number regexp returning error

### ISSUE THREAD

**Issue by gh-ecs** [Swart-lab/bleties#29]
Running bleties with the MILRAA option gives:

```
File "..miniconda3/envs/bleties/lib/python3.7/site-packages/bleties/main.py", line 35, in check_env
    dep_vers['muscle'] = re.search(r"v\S+", dep_vers['muscle']).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

Running the command:
```
muscle -version

muscle 5.1.linux64 []
Built Feb 24 2022 03:16:15

```

**Comment by kbseah** [comment]
Conda env definition file in repo has been updated to use specific Muscle version, and pull request filed for updating recipe on Bioconda (https://github.com/bioconda/bioconda-recipes/pull/34954)
